import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Download, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ReportView } from "@/components/research/report-view";
import { DeleteReportButton } from "@/components/research/delete-report-button";
import { getReport } from "@/server/research";

export const dynamic = "force-dynamic";

export default async function ReportPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const report = await getReport(id);
  if (!report) notFound();

  return (
    <div className="space-y-6">
      <Link
        href="/research"
        className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"
      >
        <ArrowLeft className="h-3.5 w-3.5" /> All reports
      </Link>

      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            <FileText className="h-3.5 w-3.5" />
            <span>Equity Research</span>
            <Badge variant="secondary" className="text-[10px]">
              {report.model === "template-fallback" ? "Template engine" : report.model}
            </Badge>
          </div>
          <h1 className="mt-1 text-2xl font-bold tracking-tight">
            {report.content.title}
          </h1>
          <p className="text-sm text-muted-foreground">
            <Link href={`/company/${report.company.ticker}`} className="hover:text-primary">
              {report.company.ticker} · {report.company.name}
            </Link>{" "}
            · {new Date(report.createdAt).toLocaleDateString()}
          </p>
        </div>
        <div className="flex gap-2">
          <Button asChild variant="outline">
            <a href={`/api/reports/${report.id}/pdf`} target="_blank" rel="noreferrer">
              <Download className="h-4 w-4" /> Export PDF
            </a>
          </Button>
          <DeleteReportButton id={report.id} redirectTo="/research" />
        </div>
      </div>

      <ReportView content={report.content} currency={report.company.currency} />

      <p className="text-xs text-muted-foreground">
        This report is for educational purposes only and is not investment
        advice. Generated by Investaschool Terminal.
      </p>
    </div>
  );
}
